name 'activemq'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures activemq'
long_description 'Installs/Configures activemq'
version '0.1.0'